gui: 
	pyside-uic virtualee.ui -o Virtualee.py
	pyside-uic sign_in.ui -o Sign_In.py
	pyside-uic pref.ui -o Pref.py
	pyside-uic about.ui -o About.py
	pyside-uic release_available.ui -o Release_Available.py 
	pyside-uic download_progress.ui -o Download_Progress.py
	pyside-uic sign_in_empleo.ui -o Sign_In_Empleo.py
	pyside-rcc icons.qrc -o icons_rc.py

